### ISSUE TITLE
[Bug] Simulator - Wrong effect for skill card 「魅惑のパフォーマンス」

### ISSUE THREAD

**Issue by Lastory** [surisuririsu/gakumas-tools#13]
In the simulator this skill card now has a permanent effect of increasing scores every turn (instead of only in the next turn).
![1](https://github.com/user-attachments/assets/c0e10f25-cae6-466c-b331-ed575771e105)

**Comment by surisuririsu** [comment]
Thanks for reporting. I've deployed a fix.
Can you reload the page and check if it's working correctly for you too?

**Comment by Lastory** [comment]
fixed confirmed.
