### ISSUE TITLE
Memories page cannot be put sidely

### ISSUE THREAD

**Issue by chenhw26** [surisuririsu/gakumas-tools#21]
Memories lost this icon
![屏幕截图 2024-09-06 195850](https://github.com/user-attachments/assets/fcfa6696-4de5-4278-b907-9899509cf6fb)
![屏幕截图 2024-09-06 195850](https://github.com/user-attachments/assets/40132384-8df5-4fc5-9077-e3f8fd2d08dc)

**Comment by surisuririsu** [comment]
ok, I made it pinnable.
