### ISSUE TITLE
An error occurs when saving a memory without entering a name

### ISSUE THREAD

**Issue by yuimarudev** [surisuririsu/gakumas-tools#5]
https://github.com/user-attachments/assets/948df134-3b81-4932-9694-71cfe449936f

(This text is machine translated, so I apologize if it is difficult to understand or strange.)

As in this video, if you create a memory without entering a name, an error will occur.
The console will output `TypeError: t.name is null`.
When this happens, you will not be able to use this tool because you will not be able to delete the memory.

**Comment by surisuririsu** [comment]
Thanks for reporting. I've deployed a fix.
Can you confirm if it's working for you too?
https://github.com/user-attachments/assets/f5e4dfe7-8e77-467b-8a33-32d7d000e69d

**Comment by yuimarudev** [comment]
It works! thank you.
